# Generated by Django 6.0.6 on 2026-06-30 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=150)),
                ('cnic', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('program_type', models.CharField(choices=[('ADP', 'ADP'), ('BS', 'BS')], max_length=20)),
                ('program', models.CharField(choices=[('ADP Information Technology', 'ADP Information Technology'), ('ADP Commerce', 'ADP Commerce'), ('ADP Arts', 'ADP Arts'), ('ADP English', 'ADP English'), ('ADP Education', 'ADP Education'), ('ADP Social Work', 'ADP Social Work'), ('BS Urdu', 'BS Urdu'), ('BS English', 'BS English'), ('BS Political Science', 'BS Political Science'), ('BS Economics', 'BS Economics'), ('BS Zoology', 'BS Zoology'), ('BS Botany', 'BS Botany'), ('BS Islamic Studies', 'BS Islamic Studies'), ('BS Physics', 'BS Physics'), ('BS Chemistry', 'BS Chemistry')], max_length=100)),
                ('matric_board', models.CharField(max_length=100)),
                ('matric_total_marks', models.IntegerField()),
                ('matric_obtained_marks', models.IntegerField()),
                ('inter_board', models.CharField(max_length=100)),
                ('inter_total_marks', models.IntegerField()),
                ('inter_obtained_marks', models.IntegerField()),
                ('photo', models.ImageField(upload_to='student_photos/')),
                ('matric_result_card', models.FileField(upload_to='documents/matric/')),
                ('inter_result_card', models.FileField(upload_to='documents/inter/')),
                ('cnic_file', models.FileField(upload_to='documents/cnic/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
