# Generated by Django 6.0.6 on 2026-06-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='inter_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='matric_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='merit_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='merit_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
