# Generated by Django 6.0.6 on 2026-06-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_admissionapplication_inter_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='is_merit_published',
            field=models.BooleanField(default=False),
        ),
    ]
